### ISSUE TITLE
Reading comment comments after Root Element closed sometimes throws `NullPointerException`

### ISSUE THREAD

**Issue by GuoHuiChen** [FasterXML/woodstox#58] opened 2018-07-23 10:47 UTC
TextBuffer.recycle()
206       char[] buf = mCurrentSegment;
207            mCurrentSegment = null;
            **this.mHasSegments = false; //MUST set false**
208            mConfig.freeMediumCBuffer(buf);

284  if (mHasSegments) {
            clearSegments();

1050  char[] curr = mCurrentSegment;
1051 int max = curr.length - mCurrentSize; //NPE

**Comment by GuoHuiChen** [comment] 2018-07-24 00:51
[430016_NG0405_20180720_V01.zip](https://github.com/FasterXML/woodstox/files/2221549/430016_NG0405_20180720_V01.zip)
This is the sample XML.

Exception in thread "main" java.lang.NullPointerException
	at com.ctc.wstx.util.TextBuffer.append(TextBuffer.java:1050)
	at com.ctc.wstx.util.TextBuffer.resetWithCopy(TextBuffer.java:291)
	at com.ctc.wstx.sr.BasicStreamReader.readComment(BasicStreamReader.java:3908)
	at com.ctc.wstx.sr.BasicStreamReader.finishToken(BasicStreamReader.java:3808)
	at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3741)
	at com.ctc.wstx.sr.BasicStreamReader.getText(BasicStreamReader.java:889)

**Comment by GuoHuiChen** [comment] 2018-08-02 00:29
Please fix this bug, Thank you!

**Comment by cowtowncoder** [comment] 2018-08-21 23:33
@GuoHuiChen Thank you for reporting the problem.

I tried simplest code I can do that creates `XMLStreamReader` for test file, but I did not get exception.
So I would like to know what is different with your usage. Could you add code you are using for reading the contents? Or something to trigger the exception.

**Comment by cowtowncoder** [comment] 2018-09-16 15:03
@GuoHuiChen I do not work for you nor take commands.

**Comment by cowtowncoder** [comment] 2019-07-14 16:17
I am able to reproduce the issue, hope to solve today -- thank you for reporting this.
The issue is that the underlying buffer is released on main xml tree closing, but then needing it to access COMMENT (or PROCESSING_INSTRUCTION) content. So need to figure out best way to avoid the problem; either by not releasing buffer as early, or, possibly, verifying is it is reallocated as needed.

**Closed** 2019-07-15 00:32 UTC
Labels: active

**Comment by cowtowncoder** [comment] 2019-07-15 00:44
Fixed, will release `5.3.0` later today.
