### ISSUE TITLE
Unexpected end of input block in end tag

### ISSUE THREAD

**Issue by vavishal** [FasterXML/woodstox#139] opened 2022-01-28 12:05 UTC
The issue is related to a SOAP web service application deployed on weblogic server
We don't have any reproducer as only happening on customer side
The request / response is consistent and is not even large i.e. less than 4096 bytes

We're encountering an odd exception in this stack and would really appreciate any insight in how to diagnose the root cause please

org.apache.camel.InvalidPayloadException: No body available of type: java.io.InputStream but has value: javax.xml.transform.dom.DOMSource@a8086c of type: javax.xml.transform.dom.DOMSource on: Message: [Body is instance of java.xml.transform.Source]. Caused by: Error during type conversion from type: java.lang.String to the required type: java.io.InputStream with value [Body is instance of java.xml.transform.Source] due java.lang.RuntimeException: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [1,598]. Exchange[Message: [Body is instance of java.xml.transform.Source]]. Caused by: [org.apache.camel.TypeConversionException - Error during type conversion from type: java.lang.String to the required type: java.io.InputStream with value [Body is instance of java.xml.transform.Source] due java.lang.RuntimeException: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [1,598]]
	at org.apache.camel.impl.MessageSupport.getMandatoryBody(MessageSupport.java:101) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.UnmarshalProcessor.process(UnmarshalProcessor.java:61) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.UnitOfWorkProducer.process(UnitOfWorkProducer.java:74) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:375) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:343) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:233) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:343) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:201) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:128) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:132) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:149) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:301) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at com.bottomline.webseries.servicemodels.platformservices.services.utility.messaging.v1.MessageProducerService.requestBody(MessageProducerService.java:68) [core-app-21.10.0-SNAPSHOT.jar:?]
	at com.bottomline.webseries.consumers.messageconverters.wpf.v6_5.WPFAsyncScoreSender.sendWirePaymentScoreRequest(WPFAsyncScoreSender.java:89) [core-app-21.10.0-SNAPSHOT.jar:?]
	at com.bottomline.webseries.consumers.messageconverters.wpf.v6_5.WPFAsyncScoreSender.processFileAsyncScore(WPFAsyncScoreSender.java:65) [core-app-21.10.0-SNAPSHOT.jar:?]
	at com.bottomline.webseries.consumers.messageconverters.wpf.v6_5.WPFMessageConverter.processFileAsyncScore(WPFMessageConverter.java:886) [core-app-21.10.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:167) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) [camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103) [camel-jms-2.14.0.jar:2.14.0]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:685) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:623) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:591) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:308) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:226) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) [spring-jms-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: org.apache.camel.TypeConversionException: Error during type conversion from type: java.lang.String to the required type: java.io.InputStream with value [Body is instance of java.xml.transform.Source] due java.lang.RuntimeException: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [1,598]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.createTypeConversionException(BaseTypeConverterRegistry.java:566) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.mandatoryConvertTo(BaseTypeConverterRegistry.java:174) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.MessageSupport.getMandatoryBody(MessageSupport.java:99) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	... 51 more
Caused by: org.apache.camel.RuntimeCamelException: java.lang.RuntimeException: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [1,598]
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1364) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.util.ObjectHelper.invokeMethod(ObjectHelper.java:1006) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.InstanceMethodTypeConverter.convertTo(InstanceMethodTypeConverter.java:79) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.doConvertTo(BaseTypeConverterRegistry.java:276) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.mandatoryConvertTo(BaseTypeConverterRegistry.java:165) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.MessageSupport.getMandatoryBody(MessageSupport.java:99) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	... 51 more
Caused by: java.lang.RuntimeException: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [1,598]
	at oracle.j2ee.ws.saaj.soap.ElementImpl.getFirstChild(ElementImpl.java:1634) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at org.apache.xml.serializer.TreeWalker.traverse(TreeWalker.java:147) ~[serializer-2.7.1.jar:2.7.1]
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:390) ~[xalan-2.7.1.jar:?]
	at org.apache.camel.converter.jaxp.XmlConverter.toResult(XmlConverter.java:132) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toResult(XmlConverter.java:116) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toByteArray(XmlConverter.java:264) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toInputStream(XmlConverter.java:1008) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at sun.reflect.GeneratedMethodAccessor414.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.apache.camel.util.ObjectHelper.invokeMethod(ObjectHelper.java:1002) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.InstanceMethodTypeConverter.convertTo(InstanceMethodTypeConverter.java:79) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.doConvertTo(BaseTypeConverterRegistry.java:276) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.mandatoryConvertTo(BaseTypeConverterRegistry.java:165) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.MessageSupport.getMandatoryBody(MessageSupport.java:99) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	... 51 more
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in end tag
 at [row,col {unknown-source}]: [1,598]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOB(StreamScanner.java:703) ~[com.fasterxml.woodstox.woodstox-core.jar:5.0.2]
	at com.ctc.wstx.sr.StreamScanner.loadMoreFromCurrent(StreamScanner.java:1076) ~[com.fasterxml.woodstox.woodstox-core.jar:5.0.2]
	at com.ctc.wstx.sr.StreamScanner.getNextCharFromCurrent(StreamScanner.java:814) ~[com.fasterxml.woodstox.woodstox-core.jar:5.0.2]
	at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3291) ~[com.fasterxml.woodstox.woodstox-core.jar:5.0.2]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2904) ~[com.fasterxml.woodstox.woodstox-core.jar:5.0.2]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1115) ~[com.fasterxml.woodstox.woodstox-core.jar:5.0.2]
	at oracle.j2ee.ws.saaj.util.ResettableXMLStreamReader.next(ResettableXMLStreamReader.java:218) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at oracle.j2ee.ws.saaj.soap.StaxHandler.moveNext(StaxHandler.java:213) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at oracle.j2ee.ws.saaj.soap.StaxHandler.staxParse(StaxHandler.java:117) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at oracle.j2ee.ws.saaj.soap.StaxHandler.staxParse(StaxHandler.java:105) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at oracle.j2ee.ws.saaj.soap.StaxHandler.staxParseNextElement(StaxHandler.java:220) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at oracle.j2ee.ws.saaj.soap.ElementImpl.realizeNextChild(ElementImpl.java:1575) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at oracle.j2ee.ws.saaj.soap.ElementImpl.getFirstChild(ElementImpl.java:1630) ~[com.oracle.webservices.orasaaj-rt-api.jar:?]
	at org.apache.xml.serializer.TreeWalker.traverse(TreeWalker.java:147) ~[serializer-2.7.1.jar:2.7.1]
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:390) ~[xalan-2.7.1.jar:?]
	at org.apache.camel.converter.jaxp.XmlConverter.toResult(XmlConverter.java:132) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toResult(XmlConverter.java:116) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toByteArray(XmlConverter.java:264) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.converter.jaxp.XmlConverter.toInputStream(XmlConverter.java:1008) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at sun.reflect.GeneratedMethodAccessor414.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.apache.camel.util.ObjectHelper.invokeMethod(ObjectHelper.java:1002) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.InstanceMethodTypeConverter.convertTo(InstanceMethodTypeConverter.java:79) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.doConvertTo(BaseTypeConverterRegistry.java:276) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.mandatoryConvertTo(BaseTypeConverterRegistry.java:165) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	at org.apache.camel.impl.MessageSupport.getMandatoryBody(MessageSupport.java:99) ~[camel-core-2.14.0-2.0-bt.jar:2.14.0]
	... 51 more

**Comment by cowtowncoder** [comment] 2022-01-28 22:12
I would need a reproduction to help, but from error condition I would suggest that this may be due to some part of processing pipeline `close()`ing input source from under Woodstox. So exception handler or something closes `InputStream` but then something else still tries to access something via `XMLStreamReader` (or event reader).
Such problems have been reported over the years. But this is almost certainly outside of Woodstox itself.

**Comment by vavishal** [comment] 2022-01-31 05:48
Can you please suggest any way on how we can determine the closing of the input source

**Comment by cowtowncoder** [comment] 2022-01-31 16:42
Since the closing (possibly auto-close) is in your code, I don't really know. It requires understanding of the code flow.

Woodstox specifically does not use any logging. The stream reader in use may still have information about the current state, if you can access it.

**Comment by mattadamson** [comment] 2022-02-21 17:15
If we look at a stack where the closed stream exception occurs at

PushbackInputStream.ensureOpen() line: 74	
PushbackInputStream.available() line: 275	
AbstractSenderConnection$ResponseTransportInputStream(TransportInputStream).available() line: 56	
BufferedInputStream.read(byte[], int, int) line: 353	
PushbackInputStream(FilterInputStream).read(byte[], int, int) line: 133	
PushbackInputStream.read(byte[], int, int) line: 186	
UTF8Reader(BaseReader).readBytes() line: 155	
UTF8Reader.loadMore(int) line: 369	
UTF8Reader.read(char[], int, int) line: 112	
MergedReader.read(char[], int, int) line: 104	
BranchingReaderSource(ReaderSource).readInto(WstxInputData) line: 89	
BranchingReaderSource.readInto(WstxInputData) line: 57	
ValidatingStreamReader(StreamScanner).loadMoreFromCurrent() line: 1065	
ValidatingStreamReader(StreamScanner).parseLocalName2(int, int) line: 1878	
ValidatingStreamReader(StreamScanner).parseLocalName(char) line: 1838	
ValidatingStreamReader(BasicStreamReader).handleStartElem(char) line: 3014	
ValidatingStreamReader(BasicStreamReader).nextFromTree() line: 2912	
ValidatingStreamReader(BasicStreamReader).next() line: 1115	
ResettableXMLStreamReader.next() line: 218	
StaxHandler11(StaxHandler).moveNext(XMLStreamReader) line: 213	
StaxHandler11(StaxHandler).staxParse(XMLStreamReader, List<QName>, boolean, boolean, boolean) line: 117	
StaxHandler11(StaxHandler).staxParse(XMLStreamReader, List<QName>, boolean, boolean) line: 105	
StaxHandler11(StaxHandler).staxParseNextElement(XMLStreamReader) line: 220	
Element11(ElementImpl).realizeNextChild() line: 1575	
Element11(ElementImpl).getFirstChild() line: 1630	
TreeWalker.traverse(Node) line: 147	
TransformerIdentityImpl.transform(Source, Result) line: 390	
XmlConverter.toResult(Source, Result, Properties) line: 145	
XmlConverter.toResult(Source, Result) line: 124	
XmlConverter.toByteArray(Source, Exchange) line: 265	
XmlConverter.toInputStream(DOMSource, Exchange) line: 773	
CamelXmlJaxpBulkConverterLoader.doConvertTo(Class<?>, Class<?>, Exchange, Object) line: 64	
CamelXmlJaxpBulkConverterLoader.convertTo(Class<?>, Class<T>, Exchange, Object) line: 35	
DefaultTypeConverter(CoreTypeConverterRegistry).doConvertTo(Class<?>, Exchange, Object, boolean) line: 461	
DefaultTypeConverter(CoreTypeConverterRegistry).doConvertTo(Class<?>, Exchange, Object, boolean, boolean) line: 356	
DefaultTypeConverter(CoreTypeConverterRegistry).mandatoryConvertTo(Class<T>, Exchange, Object) line: 272	
DefaultMessage(MessageSupport).getMandatoryBody(Class<T>) line: 115	
UnmarshalProcessor.process(Exchange, AsyncCallback) line: 58	
RedeliveryErrorHandler$SimpleTask.run() line: 395	
DefaultReactiveExecutor$Worker.executeFromQueue() line: 175	
DefaultReactiveExecutor.executeFromQueue() line: 70	
DefaultAsyncProcessorAwaitManager.await(Exchange, CountDownLatch) line: 96	
DefaultAsyncProcessorAwaitManager.process(AsyncProcessor, Exchange) line: 85	
SharedCamelInternalProcessor.process(Exchange, AsyncProcessor, Processor) line: 109	
DefaultProducerCache.send(Endpoint, Exchange, Processor) line: 189	
DefaultProducerTemplate.send(Endpoint, Exchange, Processor) line: 176	
DefaultProducerTemplate.send(Endpoint, ExchangePattern, Processor, Processor) line: 172	
DefaultProducerTemplate.requestBody(String, Object, Class<T>) line: 413	
MessageProducerService.requestBody(String, Object, Class<T>) line: 134	
CurrentDayBalanceService.sendRequest(CurrentDayBalanceRequest) line: 159	

I found the path where the stream was being closed just before causing this exeption at

PushbackInputStream.close() line: 377	
AbstractSenderConnection$ResponseTransportInputStream(TransportInputStream).close() line: 51	
HttpUrlConnection(AbstractWebServiceConnection).close() line: 133	
TransportUtils.closeConnection(WebServiceConnection) line: 45	
WebServiceTemplate.sendAndReceive(String, WebServiceMessageCallback, WebServiceMessageExtractor<T>) line: 564	
WebServiceTemplate.sendAndReceive(String, WebServiceMessageCallback, WebServiceMessageCallback) line: 531	
SpringWebserviceProducer.process(Exchange) line: 97	
AsyncProcessorConverterHelper$ProducerToAsyncProducerBridge(AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge).process(Exchange, AsyncCallback) line: 66	
SendProcessor.process(Exchange, AsyncCallback) line: 169	
RedeliveryErrorHandler$SimpleTask.run() line: 395	
DefaultReactiveExecutor$Worker.executeFromQueue() line: 175	
DefaultReactiveExecutor.executeFromQueue() line: 70	
DefaultAsyncProcessorAwaitManager.await(Exchange, CountDownLatch) line: 96	
DefaultAsyncProcessorAwaitManager.process(AsyncProcessor, Exchange) line: 85	
SharedCamelInternalProcessor.process(Exchange, AsyncProcessor, Processor) line: 109	
DefaultProducerCache.send(Endpoint, Exchange, Processor) line: 189	
DefaultProducerTemplate.send(Endpoint, Exchange, Processor) line: 176	
DefaultProducerTemplate.send(Endpoint, ExchangePattern, Processor, Processor) line: 172	
DefaultProducerTemplate.requestBody(String, Object, Class<T>) line: 413	
MessageProducerService.requestBody(String, Object, Class<T>) line: 134	
CurrentDayBalanceService.sendRequest(CurrentDayBalanceRequest) line: 159	

i will follow up in the camel group to understand more

**Comment by cowtowncoder** [comment] 2022-06-27 23:24
No reproduction, cannot do much here. Closing but can be re-filed/re-opened with more info or reproduction.

**Closed by cowtowncoder** 2022-06-27 23:24 UTC
