### ISSUE TITLE
failed to parse xml: Unrecognized property `'com.ctc.wstx.maxEntityCount'` in `woodstox:6.5`

### ISSUE THREAD

**Issue by rdulmina** [FasterXML/woodstox#171] opened 2023-04-05 17:51 UTC
I'm using `'com.fasterxml.woodstox:woodstox-core:6.5.0'` dependency to work with `XMLInputFactory` via `WstxInputFactory` In a gradle project. When I try to run the below code,

```java
xmlInputFactory = XMLInputFactory.newInstance();
xmlInputFactory.setProperty(WstxInputProperties.P_MAX_ENTITY_COUNT, 100000);
```

I'm getting `failed to parse xml: Unrecognized property 'com.ctc.wstx.maxEntityCount'`

I have included the woodstox dependency in my `build.gradle`(`implementation 'com.fasterxml.woodstox:woodstox-core:6.5.0'`).

I have debugged my code and verified that `xmlInputFactory` instance is a `WstxInputFactory` instance.

I also tried excluding `com.codehaus.woodstox` like below to make sure this is not an issue of transitive dependency conflict since `P_MAX_ENTITY_COUNT` is not available in `com.codehaus.woodstox` versions.
```gradle
configurations.implementation {
    exclude group: 'org.codehaus.woodstox', module: 'woodstox-core-asl'
}
```

Is this a bug or am I doing something wrong? It would be much appreciated if anyone can help with this. Thanx in advance.

**Comment by cowtowncoder** [comment] 2023-04-05 22:59
It definitely sounds odd, and about the only guess I have is that somehow you do have an older Woodstox version: these limits were added in version 4.2.0.
So I would try to double-check which version Gradle resolves, as well as whether there is any chance that a jar of an older version might be deployed somehow.

As to bug: if you could create a simple project with no external dependencies I could check, but I think that is quite unlikely.

**Comment by cowtowncoder** [comment] 2023-10-19 01:21
Cannot reproduce, closing.

**Closed by cowtowncoder** 2023-10-19 01:21 UTC
Labels: test-needed
