### ISSUE TITLE
WstxEOFException: Unexpected end of input block in start tag

### ISSUE THREAD

**Issue by mattadamson** [FasterXML/woodstox#44] opened 2018-03-18 15:17 UTC
Team,

We're encountering an odd intermittent exception in this stack and would really appreciate any insight in how to diagnose the root cause please.

Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected end of input block in start tag
at [row,col {unknown-source}]: [1,2753]
              at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOB(StreamScanner.java:691)
              at com.ctc.wstx.sr.StreamScanner.loadMoreFromCurrent(StreamScanner.java:1063)
              at com.ctc.wstx.sr.StreamScanner.getNextCharFromCurrent(StreamScanner.java:802)
              at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2946)
              at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2837)
              at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072)
              at oracle.j2ee.ws.saaj.util.ResettableXMLStreamReader.next(ResettableXMLStreamReader.java:216)
              at oracle.j2ee.ws.saaj.soap.StaxHandler.moveNext(StaxHandler.java:210)
              at oracle.j2ee.ws.saaj.soap.StaxHandler.staxParse(StaxHandler.java:114)
              at oracle.j2ee.ws.saaj.soap.StaxHandler.staxParse(StaxHandler.java:102)
              at oracle.j2ee.ws.saaj.soap.StaxHandler.staxParseNextElement(StaxHandler.java:217)
              at oracle.j2ee.ws.saaj.soap.ElementImpl.realizeNextChild(ElementImpl.java:1573)
              at oracle.j2ee.ws.saaj.soap.ElementImpl.getFirstChild(ElementImpl.java:1628)

The issue is related to a SOAP web service request to an ESB which works sometimes and fails with this exception in other cases. The request / response is consistent in all cases and not overly large e.g. around 3000 bytes

Many thanks

**Comment by cowtowncoder** [comment] 2018-03-18 15:59
While I can not point to specific reason, I have heard similar reports couple of times.
And in every case what has happened (as far as I have heard) has been something else somewhere in the stack has closed the underlying `InputStream`, usually due to an exception thrown (and sometimes swallowed by other code, making troubleshooting more difficult).

So I would probably see if this could be a possibility. If possible, creating a custom `InputStream` sub-class, which logs `close()` calls, might help.

**Comment by cowtowncoder** [comment] 2018-08-23 00:11
Can not reproduce as is, closing; may be reopened with test case or other pertinent information.

**Closed by cowtowncoder** 2018-08-23 00:11 UTC
Labels: test-needed
