### ISSUE TITLE
SOAP request using Apache CXF: Error writing request body to server while processing 11MB

### ISSUE THREAD

**Issue by SabarinathMohan** [FasterXML/woodstox#83] opened 2019-09-12 00:23 UTC
I have developed integration using Jboss Fuse 6.3 with JBoss EAP 6.4 AS.

This Web Service connects to SOAP endpoint using Apache CXF. It is already in LIVE and it is perfectly working fine for request size within 5 to 10 MB. We tried to test some request which are large, but request didn't reach endpoint. It stopped in apache CXF endpoint while writing request to server. Am getting below error when request XML size is more than 10MB. 

XML payload has CData.  CData inturn has XML. It is working fine if XML size is less than 10MB. I am getting below error when size of XML(CData XML) is more than 10 MB. Can you please check and advise if I need to update any configuration or property. Also let me know if there is any workaround.

Does Woodstox has any limit for CData XML?

Interceptor for {http://com.oracle.ins.webservices}SoftWS#{http://com.oracle.ins.webservices}ProcessCustom has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: Could not generate the XML stream caused by: com.ctc.wstx.exc.WstxIOException: Error writing request body to server.
	at org.apache.cxf.databinding.source.XMLStreamDataWriter.write(XMLStreamDataWriter.java:114) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.databinding.source.XMLStreamDataWriter.write(XMLStreamDataWriter.java:65) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.camel.component.cxf.HybridSourceDataBinding$1.write(HybridSourceDataBinding.java:80) [camel-cxf-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.component.cxf.HybridSourceDataBinding$1.write(HybridSourceDataBinding.java:74) [camel-cxf-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.cxf.interceptor.AbstractOutDatabindingInterceptor.writeParts(AbstractOutDatabindingInterceptor.java:137) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.wsdl.interceptors.BareOutInterceptor.handleMessage(BareOutInterceptor.java:68) [cxf-rt-wsdl-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:416) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.camel.component.cxf.CxfProducer.process(CxfProducer.java:120) [camel-cxf-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.interceptor.HandleFaultInterceptor.process(HandleFaultInterceptor.java:42) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.interceptor.HandleFaultInterceptor.process(HandleFaultInterceptor.java:42) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.interceptor.HandleFaultInterceptor.process(HandleFaultInterceptor.java:42) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.interceptor.HandleFaultInterceptor.process(HandleFaultInterceptor.java:42) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.interceptor.HandleFaultInterceptor.process(HandleFaultInterceptor.java:42) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.interceptor.HandleFaultInterceptor.process(HandleFaultInterceptor.java:42) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:196) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91) [camel-core-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112) [camel-jms-2.17.0.redhat-630310.jar:2.17.0.redhat-630310]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:555) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:515) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:485) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1103) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1095) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:992) [spring-jms-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_201]
Caused by: com.ctc.wstx.exc.WstxIOException: Error writing request body to server
	at com.ctc.wstx.sw.BaseStreamWriter.writeCData(BaseStreamWriter.java:329) [woodstox-core-asl-4.4.1.jar:4.4.1]
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:762) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:702) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:626) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.databinding.source.XMLStreamDataWriter.write(XMLStreamDataWriter.java:111) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	... 67 more
Caused by: java.io.IOException: Error writing request body to server at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3587) [rt.jar:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3570) [rt.jar:1.8.0_201]
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:69) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
	at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:291) [woodstox-core-asl-4.4.1.jar:4.4.1]
	at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:363) [woodstox-core-asl-4.4.1.jar:4.4.1]
	at com.ctc.wstx.sw.BufferingXmlWriter.writeCData(BufferingXmlWriter.java:433) [woodstox-core-asl-4.4.1.jar:4.4.1]
	at com.ctc.wstx.sw.BaseStreamWriter.writeCData(BaseStreamWriter.java:327) [woodstox-core-asl-4.4.1.jar:4.4.1]
	... 71 more

**Comment by cowtowncoder** [comment] 2019-09-12 02:53
It seems to me that Woodstox is simply throwing wrapped `IOException` caused by web server on the other end closing the connection? Could it be that it has 10 MB limit? Or if there is a proxy/gateway server that might have such limitation?

I can not think of any specific limit by Woodstox, when writing content. There are DoS limit settings on parser side (although with values that are unlikely to be reached by normal usage), but none on output side that I can remember.

**Comment by SabarinathMohan** [comment] 2019-09-12 03:03
Thanks for your response. I have other integrations which are with out CDATA content. Those are working fine without any issues even for very large XMLs. But this integration has CDATA which holds most of payload data. 

If you notice last lines on trace, exception is thrown when it is trying to WRITE to server.

Caused by: java.io.IOException: Error writing request body to server at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3587) [rt.jar:1.8.0_201]
at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3570) [rt.jar:1.8.0_201]
at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:69) [cxf-core-3.1.5.redhat-630310.jar:3.1.5.redhat-630310]
at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:291) [woodstox-core-asl-4.4.1.jar:4.4.1]
at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:363) [woodstox-core-asl-4.4.1.jar:4.4.1]
at com.ctc.wstx.sw.BufferingXmlWriter.writeCData(BufferingXmlWriter.java:433) [woodstox-core-asl-4.4.1.jar:4.4.1]
at com.ctc.wstx.sw.BaseStreamWriter.writeCData(BaseStreamWriter.java:327) [woodstox-core-asl-4.4.1.jar:4.4.1]
... 71 more
That is why I got suspicious on WoodStox, if it has anything to do with CDATA content.

**Comment by cowtowncoder** [comment] 2019-09-12 03:09
As far as I can see Woodstox is trying to write encoded content into HTTP `OutputStream`, which fails: this is not something Woodstox control but something that HTTP client does, possibly as a result of something closing the connection: http server on the other end, or some component in the network.

I do not see anything in that stack trace indicating something Woodstox has control over so you should try to see if you can see logs on the receiving end.

As to Woodstox, to help further, I would need a test case.

**Comment by SabarinathMohan** [comment] 2019-09-12 04:14
Thanks for your response. Appreciate that!

I will ask end system on other end to enable TRACE or DEBUG to check if we can get any information further.

**Closed** 2019-12-06 23:34 UTC
