### ISSUE TITLE
BasicStreamReader.getElementText() behavior doesn't match Java documentation

### ISSUE THREAD

**Issue by Caleb-An** [FasterXML/woodstox#13] opened 2016-04-15 22:08 UTC
The [documentation for XMLStreamReader](https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLStreamReader.html#getElementText--) suggests that `getElementText()` return all valid text between a `START_ELEMENT` and `END_ELEMENT`.  

With 5.0.1 and 5.0.2 woodstox, this doesn't happen for an element that contains text and then CDATA.  
Example:
`"<tag>foo<![CDATA[bar]]></tag>"`, calling `getElementText()` while at `tag` will return `"foo"`, while the example implementation from the doc comments suggests it should be `"foobar"`.

I linked the documentation from Java 8, but it's the same blurb given for previous versions as well.

**Comment by cowtowncoder** [comment] 2016-04-15 22:23
I'd need a unit test to reproduce this behavior.

**Comment by Caleb-An** [comment] 2016-04-18 20:38
Here's a unit test:
1. clone from [my fork](https://github.com/Caleb-An/woodstox.git)
2. checkout branch `get_ele_text_unit_test`
3. The test is `testGetMixedContentElementText()` under `TestGetElement.java`

thanks for looking into this!

**Comment by cowtowncoder** [comment] 2016-04-19 02:54
Ok it looks like I can reproduce it with the test case. Good!

Oddly enough looks like this passes if coalescing is disabled.

**Comment by cowtowncoder** [comment] 2016-04-19 03:42
Thank you for the reproduction; I was able to fix this. Will be in 5.0.3, when that gets released -- this is the first fix, so I'll wait for a bit to see if any other problems might be found.

**Closed** 2016-04-19 03:41 UTC
